import { defineContentScript } from '#imports';
import type { AdBlockLevel, DomRule } from '@blur/core';
import {
  DomRuleEngine,
  deepQuerySelectorAll,
  ruleAppliesTo,
  resolveAdBlockSettings,
  isAllowlisted,
  DEFAULT_ADBLOCK_SETTINGS,
} from '@blur/core';
import type { AdBlockSiteConfigX, CustomFilters } from '../utils/adblock-types';
import { settingsItem, siteConfigsItem, customFiltersItem } from '../utils/storage';
import { addFilter, customRulesForHost } from '../utils/custom-filters';
import { startPicker } from '../utils/element-picker';
// Bundled at build time (regenerated by `npm run build:rules`). Importing rather
// than fetching avoids needing a web_accessible_resources entry for the content
// script, and the set is small and curated (see IMPLEMENTATION.md).
import cosmeticData from '@/public/rules/cosmetic.json';

const cosmetic: { generic: string[]; siteSpecific: Record<string, string[]> } = cosmeticData;

/**
 * Cosmetic `hide` rules from the enabled lists' cosmetic sections. Cosmetic
 * filtering uses `action: 'hide'` (display:none) via the SAME DomRuleEngine the
 * blur extension drives with `action: 'blur'`; only the CSS action differs.
 *
 * At `standard`, only SITE-SPECIFIC selectors. At `aggressive`, also the generic
 * ones — generic cosmetic filtering is what breaks sites and burns CPU, so it
 * stays off by default (PLAN.md §4.5).
 */
function cosmeticRules(level: AdBlockLevel): DomRule[] {
  if (level === 'off') return [];
  const rules: DomRule[] = [];
  for (const [host, selectors] of Object.entries(cosmetic.siteSpecific)) {
    for (const selector of selectors) rules.push({ selector, action: 'hide', hostnames: [host] });
  }
  if (level === 'aggressive') {
    for (const selector of cosmetic.generic) rules.push({ selector, action: 'hide' });
  }
  return rules;
}

interface PickerMessage {
  type: 'startPicker';
}

export default defineContentScript({
  matches: ['<all_urls>'],
  // document_start so hidden elements never flash before being hidden — the
  // injected user stylesheet must land before first paint (PLAN.md §3.1).
  runAt: 'document_start',
  cssInjectionMode: 'ui',
  async main(ctx) {
    const hostname = location.hostname;
    let global = await settingsItem.getValue().catch(() => DEFAULT_ADBLOCK_SETTINGS);
    let siteConfigs = await siteConfigsItem
      .getValue()
      .catch((): Record<string, AdBlockSiteConfigX> => ({}));
    let customFilters = await customFiltersItem.getValue().catch((): CustomFilters => ({}));

    // Whether cosmetic filtering should currently run for this host. Recomputed
    // live: the full allowlist and the master switch stop everything; the per-site
    // `disableCosmetic` flag (feature §3) keeps network blocking but stops hiding.
    function cosmeticActive(): boolean {
      const settings = resolveAdBlockSettings(global, siteConfigs[hostname]);
      if (!settings.enabled || isAllowlisted(settings.allowlist, hostname)) return false;
      if (siteConfigs[hostname]?.disableCosmetic === true) return false;
      return true;
    }

    // The hide rules that apply right now, given the current level + user filters.
    function computeRules(): DomRule[] {
      const settings = resolveAdBlockSettings(global, siteConfigs[hostname]);
      return [...cosmeticRules(settings.adblock.level), ...customRulesForHost(customFilters, hostname)];
    }

    let currentRules: DomRule[] = computeRules();

    // Cosmetic hides are counted EXACTLY on every browser, unlike network blocks.
    //
    // ⚠️ We CANNOT use `DomRuleEngine.stats.hidden`: the engine counts via an
    // IntersectionObserver, which never reports `display:none` elements as
    // intersecting (they have no layout box), so its hidden count is always 0.
    // Instead we count distinct elements matched by our applicable hide selectors
    // ourselves — an exact figure — while still letting the engine own the actual
    // CSS injection and shadow-root traversal.
    //
    // We report a DELTA since the last message (not the cumulative count): the MV3
    // background is torn down after ~30s idle, so a background-derived baseline
    // would reset and double-count the next full report. This content script
    // survives SW death and owns `reportedTotal`. Reports are coalesced to at most
    // one per REPORT_INTERVAL_MS to avoid a message storm during the initial sweep.
    const REPORT_INTERVAL_MS = 500;
    let reportedTotal = 0;
    let latestTotal = 0;
    let timer: ReturnType<typeof setTimeout> | undefined;

    function send(): void {
      timer = undefined;
      const delta = latestTotal - reportedTotal;
      if (delta === 0) return;
      reportedTotal = latestTotal;
      void browser.runtime.sendMessage({
        type: 'reportCosmeticHidden',
        tabId: -1,
        total: latestTotal,
        delta,
      });
    }

    // Only the selectors that apply to THIS host (site-specific rules are scoped;
    // generic + user rules apply everywhere). Counting the combined selector of
    // just these yields the exact number of elements our CSS hides. Rebuilt live
    // whenever the rule set changes.
    let countSelectors = new Set(
      currentRules.filter((r) => ruleAppliesTo(r, hostname)).map((r) => r.selector),
    );
    const counted = new WeakSet<Element>();

    function recount(): void {
      if (countSelectors.size === 0) return;
      const selector = [...countSelectors].join(',');
      let els: Element[];
      try {
        els = deepQuerySelectorAll(document, selector);
      } catch {
        // A malformed user selector must never throw and kill counting.
        return;
      }
      let added = 0;
      for (const el of els) {
        if (!counted.has(el)) {
          counted.add(el);
          added += 1;
        }
      }
      if (added > 0) {
        latestTotal += added;
        if (timer === undefined) timer = setTimeout(send, REPORT_INTERVAL_MS);
      }
    }

    // Lazy engine: pages with no applicable rules pay nothing (no observers), but
    // the element picker can spin one up on demand when the user adds a rule.
    let engine: DomRuleEngine | undefined;
    function ensureEngine(): void {
      if (engine) return;
      engine = new DomRuleEngine({
        rules: currentRules,
        blurRadius: 0, // inert: cosmetic hides rather than blurs
        reveal: 'never',
        hostname,
        // The engine drives DOM sweeps/drains on mutation; piggyback our own exact
        // count on each tick rather than adding a second MutationObserver.
        onStatsChange: () => recount(),
      });
      engine.start();
      recount();
    }

    // Reflect the current settings/site-config/custom-filter state onto the live
    // page. Called at startup AND from storage watchers, so toggling cosmetic,
    // picking a filter, changing strictness or allowlisting a site takes effect on
    // an already-open tab with no reload. When cosmetic is switched off (allowlist,
    // master toggle, or per-site disable) the engine is stopped, which removes its
    // injected stylesheet and un-hides everything.
    function apply(): void {
      if (!cosmeticActive()) {
        currentRules = [];
        countSelectors = new Set();
        engine?.stop();
        engine = undefined;
        return;
      }
      currentRules = computeRules();
      countSelectors = new Set(
        currentRules.filter((r) => ruleAppliesTo(r, hostname)).map((r) => r.selector),
      );
      if (engine) engine.updateRules(currentRules);
      else ensureEngine();
      recount();
    }

    if (cosmeticActive() && currentRules.length > 0) ensureEngine();

    // Add a user-picked selector: persist it (which re-applies via the watcher),
    // and reflect it immediately so the click feels instant.
    async function addUserRule(selector: string): Promise<void> {
      customFilters = addFilter(customFilters, hostname, selector);
      apply();
      await customFiltersItem.setValue(customFilters).catch(() => {});
    }

    // Live propagation: re-apply when any input the page depends on changes, so
    // changes made in the popup/options reach open tabs without a reload.
    const unwatchSettings = settingsItem.watch((next) => {
      if (next) global = next;
      apply();
    });
    const unwatchSiteConfigs = siteConfigsItem.watch((next) => {
      siteConfigs = next ?? {};
      apply();
    });
    const unwatchCustom = customFiltersItem.watch((next) => {
      customFilters = next ?? {};
      apply();
    });

    // Element picker (feature §1) + context-menu "Block this element": the
    // background/popup sends `startPicker`; only the top frame runs it.
    let activePicker: { cancel: () => void } | undefined;
    browser.runtime.onMessage.addListener((message: PickerMessage) => {
      if (message?.type !== 'startPicker') return;
      if (window.top !== window) return;
      activePicker?.cancel();
      activePicker = startPicker((selector) => {
        activePicker = undefined;
        void addUserRule(selector);
      }, () => {
        activePicker = undefined;
      });
    });

    ctx.onInvalidated(() => {
      if (timer !== undefined) clearTimeout(timer);
      activePicker?.cancel();
      unwatchSettings();
      unwatchSiteConfigs();
      unwatchCustom();
      // Flush any pending delta so the last window of hides isn't lost.
      send();
      engine?.stop();
    });
  },
});
