import { browser } from '#imports';

/**
 * `browser.runtime.getURL` is typed against a WXT-generated union of known public
 * files. `rules/manifest.json` and `rules/cosmetic.json` are GENERATED by
 * `build:rules`, so they may be absent from that union when `tsc` runs before the
 * rulesets are built. Widening the parameter here decouples compile from build
 * order without reaching for `any`.
 */
export function publicUrl(path: string): string {
  const getURL = browser.runtime.getURL as (p: string) => string;
  return getURL(path);
}
